# ==========================================
# Developer Setup Configuration
# ==========================================


TIMEZONE=Asia/Kolkata


PYTHON_VERSION=3.12


NODE_VERSION=latest


AI_ENV_NAME=ai


WORKSPACE=$HOME/Developer


DEFAULT_BRANCH=main